spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bangle_db?serverTimezone=UTC&characterEncoding=UTF-8&collation=utf8mb4_bin
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
      use_sql_comments: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect